# networks:
#   my-network:
#     external: true
services:
  api-server:
    build:
      context: .
      dockerfile: src/Dockerfile
    volumes:
      - default-data:/home/default
    ports:
      - "8888:80"
    depends_on:
      - sftp-server
    # networks:
    # - my-network

  sftp-server:
    build: .
    ports:
      - "8890:22"
    volumes:
      - default-data:/home/default
    # networks:
    # - my-network

volumes:
  default-data:
